// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnbqzhKv6_OoF5kuI2F3rYKdFnwmmpdyA',
    appId: '1:204438523227:web:07418d2a6dd08bc4e9de7e',
    messagingSenderId: '204438523227',
    projectId: 'stock-management-679da',
    authDomain: 'stock-management-679da.firebaseapp.com',
    storageBucket: 'stock-management-679da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7cnHEZyFc8fA95NUdqZWashZvZVAmTfs',
    appId: '1:204438523227:android:d38d0ed4fbe1538be9de7e',
    messagingSenderId: '204438523227',
    projectId: 'stock-management-679da',
    storageBucket: 'stock-management-679da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx9A-xsozNJv8udUF8CIX5Lz2I4qM4a4Q',
    appId: '1:204438523227:ios:4531c50595cc891fe9de7e',
    messagingSenderId: '204438523227',
    projectId: 'stock-management-679da',
    storageBucket: 'stock-management-679da.appspot.com',
    iosClientId: '204438523227-056er5jbt37qbr5jkcst27oh3kaul8tc.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx9A-xsozNJv8udUF8CIX5Lz2I4qM4a4Q',
    appId: '1:204438523227:ios:4531c50595cc891fe9de7e',
    messagingSenderId: '204438523227',
    projectId: 'stock-management-679da',
    storageBucket: 'stock-management-679da.appspot.com',
    iosClientId: '204438523227-056er5jbt37qbr5jkcst27oh3kaul8tc.apps.googleusercontent.com',
    iosBundleId: 'com.example.stockManagement',
  );
}
